add_activity:
  name: Add activity
  description: Add an activity to the list.
  fields:
    name:
      name: Name
      description: The name of the item to add.
      required: true
      example: Running
      selector:
        text:
    category:
      name: Category
      description: The name of the item to add.
      required: true
      example: Workout
      selector:
        text:
    frequency:
      name: Frequency
      description: The frequency of the activity
      required: true
      example: 7:0:0
      selector:
        duration:
          enable_day: true
    last_completed:
      name: Last Completed
      description: Last time the activity was done
      required: false
      selector:
        datetime:
    icon:
      name: Icon
      required: false
      selector:
        icon:

remove_activity:
  name: Remove Activity
  description: Remove the first item with matching name from the list.
  fields:
    entity_id:
      name: Entity ID
      description: The id of the entity to update
      required: true
      example: Workout
      selector:
        entity:
          filter:
            - integration: "activity_manager"

update_activity:
  name: Update Activity
  description: Update the activity
  fields:
    entity_id:
      name: Entity ID
      description: The id of the entity to update
      required: true
      example: Workout
      selector:
        entity:
          filter:
            - integration: "activity_manager"
    now:
      name: Now
      description: Preferred over last completed
      required: false
      selector:
        boolean:
    last_completed:
      name: Last Completed
      description: Last time the activity was done
      required: false
      selector:
        datetime:
    category:
      name: Category
      description: The category
      required: false
      example: Workout
      selector:
        text:
    frequency:
      name: Frequency
      description: The frequency of the activity
      required: false
      example: 07:00:00
      selector:
        duration:
          enable_day: true
    icon:
      name: Icon
      required: false
      selector:
        icon:
